//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SniperdyneDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicles
    {
        [Key]
        public int VehiclesID { get; set; }

        [Display(Name = "Vehicle Name")]
        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string VehiclesName { get; set; }

        [Display(Name = "Vehicle Type")]
        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string VehiclesType { get; set; }

        [Display(Name = "Upload Image")]
        [Required]

        //[ValidateFile(ErrorMessage = "Please select a PNG image smaller than 1MB")]
        [DataType(DataType.ImageUrl)]
        public byte[] VehiclessImages { get; set; }
    }
}
